# Generated by Django 5.1.2 on 2024-10-31 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_data', models.BinaryField(blank=True, editable=True, null=True)),
                ('fingerprint_data', models.TextField(blank=True, help_text='Stores WebAuthn fingerprint credential data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfaprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
